In [70]:
import numpy as np

첫번째밭 = [
    [1, 0, 0, 0, 0],
    [0, 0, 1, 0, 1],
    [0, 0, 1, 0, 1],
    [0, 0, 1, 0, 1],
    [0, 0, 1, 0, 1]
]

두번째밭 = [
    [0, 0, 0, 0, 1],
    [0, 0, 0, 0, 3],
    [0, 0, 0, 0, 4],
    [0, 2, 0, 0, 2],
    [4, 5, 0, 2, 0]
]


In [40]:
np.array(첫번째밭)-np.rot90(두번째밭, 1) 

array([[ 0, -3, -4, -2,  0],
       [ 0,  0,  1,  0, -1],
       [ 0,  0,  1,  0,  1],
       [ 0,  0,  1, -2, -4],
       [ 0,  0,  1,  0, -3]])

In [20]:
np.array(첫번째밭)*np.rot90(두번째밭, 1) 

array([[1, 0, 0, 0, 0],
       [0, 0, 0, 0, 2],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5],
       [0, 0, 0, 0, 4]])

In [22]:
np.array(첫번째밭)@np.rot90(두번째밭, 1) 

array([[1, 3, 4, 2, 0],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 4]])

In [28]:
정답 = np.rot90(두번째밭, 1) +np.array(첫번째밭)
''.join([str(i) for i in 정답[0]])

'23420'

In [32]:
int(''.join([str(i) for i in 정답[0]]), 8)

10000

In [37]:
chr(int(''.join([str(i) for i in 정답[1]]), 8))

'C'

In [43]:
for k in range(5) : 
    print(chr(int(''.join([str(i) for i in 정답[k]]), 8)))

✐
C
A
V
E


In [71]:
import numpy as np

첫번째밭 = [
    [1, 0, 0, 0, 0],
    [0, 0, 1, 0, 1],
    [0, 0, 1, 0, 1],
    [0, 0, 1, 0, 1],
    [0, 0, 1, 0, 1]
]


두번째밭 = [
    [0, 0, 0, 0, 1],
    [0, 0, 0, 0, 3],
    [0, 0, 0, 0, 4],
    [0, 2, 0, 0, 2],
    [4, 5, 0, 2, 0]
]


In [73]:
np.rot90(두번째밭, 1) 

두번째밭

[[0, 0, 0, 0, 1],
 [0, 0, 0, 0, 3],
 [0, 0, 0, 0, 4],
 [0, 2, 0, 0, 2],
 [4, 5, 0, 2, 0]]

In [75]:
import numpy as np

첫번째밭 = [
    [1, 0, 0, 0, 0],
    [0, 0, 1, 0, 1],
    [0, 0, 1, 0, 1],
    [0, 0, 1, 0, 1],
    [0, 0, 1, 0, 1]
]

두번째밭 = [
    [0, 0, 0, 0, 1],
    [0, 0, 0, 0, 3],
    [0, 0, 0, 0, 4],
    [0, 2, 0, 0, 2],
    [4, 5, 0, 2, 0]
]


In [77]:
np.rot90(두번째밭, 1) + np.array(첫번째밭)

array([[2, 3, 4, 2, 0],
       [0, 0, 1, 0, 3],
       [0, 0, 1, 0, 1],
       [0, 0, 1, 2, 6],
       [0, 0, 1, 0, 5]])

In [79]:
np.rot90(두번째밭, 1) - np.array(첫번째밭)

array([[ 0,  3,  4,  2,  0],
       [ 0,  0, -1,  0,  1],
       [ 0,  0, -1,  0, -1],
       [ 0,  0, -1,  2,  4],
       [ 0,  0, -1,  0,  3]])

In [80]:
array = np.rot90(두번째밭, 1)
array

array([[1, 3, 4, 2, 0],
       [0, 0, 0, 0, 2],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 2, 5],
       [0, 0, 0, 0, 4]])